apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-users-deployment
  labels:
    app: api-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-users
  template:
    metadata:
      labels:
        app: api-users
    spec:
      containers:
        - name: api-users
          image: ${DOCKER_IMAGE}
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: localhost
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          readinessProbe:
            httpGet:
              path: /users/health
              port: 8080
            periodSeconds: 5
          ports:
            - name: api-users
              containerPort: 8080
              protocol: TCP
        - name: redis
          image: redis
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: api-users
  labels:
    app: api-users
spec:
  selector:
    app: api-users
  type: NodePort
  ports:
    - name: api-users
      port: 8080
      protocol: TCP
      targetPort: 8080
